import Head from 'next/head'
import { Container } from 'react-bootstrap';
import { getPosts, getPostBySlug } from '../../services/api';


export default function Home({ post }) {
  return (
    <>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className='my-5'>
        <article>
          <h1>{post?.title}</h1>
          <div className='post-content' dangerouslySetInnerHTML={{ __html: post?.content }} />
        </article>
      </Container>
    </>
  )
}


export async function getStaticPaths() {
  const posts = await getPosts();
  return {
    paths: posts?.map(post => `/posts/${post.slug}`) || [],
    fallback: true,
  }
}

export async function getStaticProps({ params }) {
  const post = await getPostBySlug(params.url)
  return { props: { post } }
}

