import Head from 'next/head'
import { getPosts, getPostBySlug } from '../../services/api';


export default function Home({ post }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="post-container">
        <h1>{ post?.title }</h1>
        <div className='post-content'  dangerouslySetInnerHTML={{ __html: post?.content }} />
      </div>
    </>
  )
}


export async function getStaticPaths(){
  const posts = await getPosts();
  return {
    paths: posts?.map( post => `/posts/${post.slug}`) || [],
    fallback: true,
  }
}

export async function getStaticProps({params}){
  const post = await getPostBySlug(params.url)
  return { props: { post } }
}

