import Head from 'next/head'
import { getPosts } from '../../services/api';
import ArticleList from '../../components/ArticleList';

function Posts({ posts }) {
	return (
		<>
			<Head>
				<title>Weart.hu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ArticleList posts={posts} limit={9} />
		</>
	)
}

export default Posts

export async function getStaticProps() {
	const posts = await getPosts();
	return { props: { posts } }
}