import Head from 'next/head'
import Hero from '../components/home/Hero'
import Logo from '../components/home/Logo'
import Portfolio from '../components/home/Portfolio'
import Services from '../components/home/Services'
import Testimonials from '../components/home/Testimonials'
import About from '../components/home/About'
import Process from '../components/home/Process'
import Blog from '../components/home/Blog'
import { homePageQuery } from '../helpers/queries'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Weart.hu - Egyed Balázs, JS, React és WordPress fejlesztő</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero data={data.pageBy.homeHero} />
      <Logo data={data.pageBy.homeLogos.homelogos} />
      <Services data={data.pageBy.homeServices} />
      <Portfolio />
      {/* <Process /> */}
      <Testimonials />
      <About />
      {/* <Blog /> */}
    </>
  )
}

export async function getStaticProps(){

  const client = new ApolloClient({
    uri: process.env.WP,
    cache: new InMemoryCache()
  });

  const {data} = await client.query({
    query: homePageQuery
  })

  return {
    props: {
      data: data
    }
  }
}