import { homePageQuery } from '../helpers/queries'
import { ApolloClient, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import Hero from '../components/home/Hero'
import Logo from '../components/home/Logo'
import Portfolio from '../components/home/Portfolio'
import Services from '../components/home/Services'
import Testimonials from '../components/home/Testimonials'
import About from '../components/home/About'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Weart.hu - Egyed Balázs, JS, React és WordPress fejlesztő</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <Logo />
      <Services />
      <Portfolio data={data?.page.homePortfolio} />
      <Testimonials data={data?.acfOptionsGlobalOptions.testimonial} />
      <About />
    </>
  )
}

export async function getStaticProps(){

  const client = new ApolloClient({
    uri: process.env.WP,
    cache: new InMemoryCache()
  });

  const {data} = await client.query({
    query: homePageQuery
  })

  return {
    props: {
      data: data
    }
  }
}