import Head from 'next/head'
import ArticleList from '../components/ArticleList';
import Hero from '../components/Hero';
import Menu from '../components/Menu';
import { get, getql } from '../services/api';

export default function Home({ posts, postql }) {
  console.log(postql)
  return (
    <div className='wrapper'>
      <Head>
        <title>Weart.hu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ArticleList posts={ postql } />
    </div>
  )
}

export async function getStaticProps(){
  const posts = await get('posts');

  const q = await getql(`query {
    posts {
      edges {
        node {
          excerpt
          slug
          title
          date
          id
        }
      }
    }
  }`);

  const postql = q.data.posts.edges.map(item => item.node);

  return { props: { posts, postql } }
}